void^ memcpy(void^ dst, void^ src, long n);
void^ memmove(void^ dst, void^ src, long n);
void^ memset(void^ s, int c, long n);
int memcmp(void^ s1, void^ s2, long n);
void memchr(void^ s, int c, long n);
char^ strcpy(char^ dst, char^ src);
char^ strncpy(char^ dst, char^ src, long n);
char^ strcat(char^ dst, char^ src);
char^ strncat(char^ dst, char^ src, long n);
int strcmp(char^ s1, char^ s2);
int strncmp(char^ s1, char^ s2, long n);
int strcoll(char^ s1, char^ s2);
char^ strdup(char^ s);
char^ strndup(char^s, long n);
char^ strchr(char^ s, int c);
//char^ strnchr(char^ s, int c, long n);
char^ strrchr(char^ s, int c);
char^ strpbrk(char^ s, char^ accept);
char^ strstr(char^ haystack, char^ needle);
char^ strtok(char^ s, char^ delim);
void^ memmem(void^ hs, long hslen, void^ ned, long nedlen);
long strlen(char^ s);
long strnlen(char^ st, long mlen);
char^ strerror(int errnum);
char^ basename(char ^filenm);
